# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0556a627acc0d4f348de5e3cf1cc7947c3528377348649534d92f9cf56e66b98af2c76e257947ac2ee79762e8a939bbcde735312df6a43b1a1aa367538b8050d

test:
  secret_key_base: c67f0b6892836fb667dabca8e975d7e22e3df13564a99f41b26894834392b2b736de157e2f9e13097201764217a78253931053fe327380a1eb0e582f77c15579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
